preset: simple
changelog:
  path: build/CHANGELOG.md
  template: "config/CHANGELOG.tpl"
  sections:
    "Added": "^feat$"
    "Fixed": "^fix$"
  substitutions:
    "(?m)#([0-9]+)(?s)": "[#%s](https://github.com/{{#environmentVariable}}GITHUB_REPOSITORY_OWNER{{/environmentVariable}}/CursedPublish/issues/%s)"
releaseTypes:
  enabled:
    - mainline
    - integration
    - internal
  publicationServices:
    - github
  items:
    mainline:
      description: "{{#fileContent}}build/CHANGELOG.md{{/fileContent}}"
      filterTags: "^({{configuration.releasePrefix}})?([0-9]\\d*)\\.([0-9]\\d*)\\.([0-9]\\d*)$"
      gitPush: "true"
      gitTag: "true"
      matchBranches: "^(master|main)$"
      matchEnvironmentVariables:
        CI: "^true$"
      matchWorkspaceStatus: "CLEAN"
      publish: "true"
    integration:
      collapseVersions: true
      collapsedVersionQualifier: "{{#sanitizeLower}}{{branch}}{{/sanitizeLower}}"
      description: "{{#file.content}}build/CHANGELOG.md{{/file.content}}"
      filterTags: "^({{configuration.releasePrefix}})?([0-9]\\d*)\\.([0-9]\\d*)\\.([0-9]\\d*)(-(develop|development|integration|latest)(\\.([0-9]\\d*))?)$"
      gitCommit: "false"
      gitPush: "true"
      gitTag: "true"
      matchBranches: "^(develop|development|integration|latest)$"
      matchWorkspaceStatus: "CLEAN"
      publish: "true"
      publishPreRelease: "true"
      versionRangeFromBranchName: false
    internal:
      description: "{{#fileContent}}build/CHANGELOG.md{{/fileContent}}"
      collapseVersions: true
      collapsedVersionQualifier: "internal"
      gitPush: "false"
      gitTag: "false"
      publish: "false"
      publishPreRelease: "true"
services:
  github:
    type: GITHUB
    options:
      AUTHENTICATION_TOKEN: "{{#environmentVariable}}GITHUB_TOKEN{{/environmentVariable}}"
      REPOSITORY_OWNER: "{{#environmentVariable}}GITHUB_REPOSITORY_OWNER{{/environmentVariable}}"
      REPOSITORY_NAME: "CursedPublish"
stateFile: "build/.nyx-state.json"