name: Build

on:
  workflow_dispatch:
  workflow_call:
  push:
  pull_request:

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gradle: [ '8.6-rc-1', '8.5', '8.0.2', '7.0.2' ]
        java: [ 8, 11, 17, 21 ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ matrix.gradle }}
          dependency-graph: generate
          artifact-retention-days: 1
      - name: Build
        run: gradle -s build --scan
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '**/build/test-results/*/TEST-*.xml'
          check_name: "JUnit Test Report (Gradle ${{ matrix.gradle }}, Java ${{ matrix.java }})"
