name: Validate Gradle Wrapper

on:
  push:
    paths:
      - gradlew
      - gradlew.bat
      - gradle/wrapper/
  pull_request:
    paths:
      - gradlew
      - gradlew.bat
      - gradle/wrapper/

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1