name: Update Gradle Wrapper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

jobs:
  update-gradle-wrapper:
    name: Update Gradle Wrapper
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          labels: deps